#############################################################################
# Makefile for building: HMS
# Generated by qmake (2.01a) (Qt 4.4.3) on: Wed Feb 25 21:42:05 2009
# Project:  HMS.pro
# Template: app
# Command: /usr/bin/qmake -unix -o Makefile HMS.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_SQL_LIB -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++ -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4/QtGui -I/usr/include/qt4/QtSql -I/usr/include/qt4/QtSql -I/usr/include/qt4 -I. -Isrc -Iui -Iheaders -Ibuild -Ibuild
LINK          = g++
LFLAGS        = -Wl,--no-undefined
LIBS          = $(SUBLIBS)  -L/usr/lib -lQtSql -lQtGui -lQtCore -lpthread
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -sf
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = build/

####### Files

SOURCES       = src/login.cpp \
		src/main.cpp \
		src/mainwindow.cpp \
		src/qsqlconnectiondialog.cpp \
		src/AdminCheck.cpp \
		src/AddRoom.cpp \
		src/check.cpp \
		src/show.cpp \
		src/liveinfo.cpp build/moc_login.cpp \
		build/moc_mainwindow.cpp \
		build/moc_qsqlconnectiondialog.cpp \
		build/moc_AdminCheck.cpp \
		build/moc_AddRoom.cpp \
		build/moc_check.cpp \
		build/moc_liveinfo.cpp \
		build/moc_show.cpp \
		qrc_HMS.cpp
OBJECTS       = build/login.o \
		build/main.o \
		build/mainwindow.o \
		build/qsqlconnectiondialog.o \
		build/AdminCheck.o \
		build/AddRoom.o \
		build/check.o \
		build/show.o \
		build/liveinfo.o \
		build/moc_login.o \
		build/moc_mainwindow.o \
		build/moc_qsqlconnectiondialog.o \
		build/moc_AdminCheck.o \
		build/moc_AddRoom.o \
		build/moc_check.o \
		build/moc_liveinfo.o \
		build/moc_show.o \
		build/qrc_HMS.o
DIST          = /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		HMS.pro
QMAKE_TARGET  = HMS
DESTDIR       = 
TARGET        = HMS

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): build/ui_configdlg.h build/ui_login.h build/ui_mainwindow.h build/ui_qsqlconnectiondialog.h build/ui_record.h build/ui_addroom.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: HMS.pro  /usr/share/qt4/mkspecs/linux-g++/qmake.conf /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/lib/libQtSql.prl \
		/usr/lib/libQtGui.prl \
		/usr/lib/libQtCore.prl
	$(QMAKE) -unix -o Makefile HMS.pro
/usr/share/qt4/mkspecs/common/g++.conf:
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/lib/libQtSql.prl:
/usr/lib/libQtGui.prl:
/usr/lib/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -unix -o Makefile HMS.pro

dist: 
	@$(CHK_DIR_EXISTS) build/HMS1.0.0 || $(MKDIR) build/HMS1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) build/HMS1.0.0/ && $(COPY_FILE) --parents headers/login.h headers/mainwindow.h headers/qsqlconnectiondialog.h headers/AdminCheck.h headers/AddRoom.h headers/check.h headers/liveinfo.h headers/show.h build/HMS1.0.0/ && $(COPY_FILE) --parents HMS.qrc build/HMS1.0.0/ && $(COPY_FILE) --parents src/login.cpp src/main.cpp src/mainwindow.cpp src/qsqlconnectiondialog.cpp src/AdminCheck.cpp src/AddRoom.cpp src/check.cpp src/show.cpp src/liveinfo.cpp build/HMS1.0.0/ && $(COPY_FILE) --parents ui/configdlg.ui ui/login.ui ui/mainwindow.ui ui/qsqlconnectiondialog.ui ui/record.ui ui/addroom.ui build/HMS1.0.0/ && (cd `dirname build/HMS1.0.0` && $(TAR) HMS1.0.0.tar HMS1.0.0 && $(COMPRESS) HMS1.0.0.tar) && $(MOVE) `dirname build/HMS1.0.0`/HMS1.0.0.tar.gz . && $(DEL_FILE) -r build/HMS1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: build/moc_login.cpp build/moc_mainwindow.cpp build/moc_qsqlconnectiondialog.cpp build/moc_AdminCheck.cpp build/moc_AddRoom.cpp build/moc_check.cpp build/moc_liveinfo.cpp build/moc_show.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) build/moc_login.cpp build/moc_mainwindow.cpp build/moc_qsqlconnectiondialog.cpp build/moc_AdminCheck.cpp build/moc_AddRoom.cpp build/moc_check.cpp build/moc_liveinfo.cpp build/moc_show.cpp
build/moc_login.cpp: build/ui_login.h \
		headers/login.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) headers/login.h -o build/moc_login.cpp

build/moc_mainwindow.cpp: build/ui_mainwindow.h \
		headers/qsqlconnectiondialog.h \
		build/ui_qsqlconnectiondialog.h \
		headers/AdminCheck.h \
		headers/AddRoom.h \
		build/ui_addroom.h \
		headers/mainwindow.h \
		headers/show.h \
		headers/liveinfo.h \
		headers/check.h \
		headers/mainwindow.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) headers/mainwindow.h -o build/moc_mainwindow.cpp

build/moc_qsqlconnectiondialog.cpp: build/ui_qsqlconnectiondialog.h \
		headers/qsqlconnectiondialog.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) headers/qsqlconnectiondialog.h -o build/moc_qsqlconnectiondialog.cpp

build/moc_AdminCheck.cpp: headers/AdminCheck.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) headers/AdminCheck.h -o build/moc_AdminCheck.cpp

build/moc_AddRoom.cpp: build/ui_addroom.h \
		headers/mainwindow.h \
		build/ui_mainwindow.h \
		headers/qsqlconnectiondialog.h \
		build/ui_qsqlconnectiondialog.h \
		headers/AdminCheck.h \
		headers/AddRoom.h \
		headers/show.h \
		headers/liveinfo.h \
		headers/check.h \
		headers/AddRoom.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) headers/AddRoom.h -o build/moc_AddRoom.cpp

build/moc_check.cpp: headers/check.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) headers/check.h -o build/moc_check.cpp

build/moc_liveinfo.cpp: headers/check.h \
		headers/liveinfo.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) headers/liveinfo.h -o build/moc_liveinfo.cpp

build/moc_show.cpp: headers/liveinfo.h \
		headers/check.h \
		headers/show.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) headers/show.h -o build/moc_show.cpp

compiler_rcc_make_all: qrc_HMS.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_HMS.cpp
qrc_HMS.cpp: HMS.qrc \
		HMS.qrc
	/usr/bin/rcc -name HMS HMS.qrc -o qrc_HMS.cpp

compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: build/ui_configdlg.h build/ui_login.h build/ui_mainwindow.h build/ui_qsqlconnectiondialog.h build/ui_record.h build/ui_addroom.h
compiler_uic_clean:
	-$(DEL_FILE) build/ui_configdlg.h build/ui_login.h build/ui_mainwindow.h build/ui_qsqlconnectiondialog.h build/ui_record.h build/ui_addroom.h
build/ui_configdlg.h: ui/configdlg.ui
	/usr/bin/uic-qt4 ui/configdlg.ui -o build/ui_configdlg.h

build/ui_login.h: ui/login.ui
	/usr/bin/uic-qt4 ui/login.ui -o build/ui_login.h

build/ui_mainwindow.h: ui/mainwindow.ui
	/usr/bin/uic-qt4 ui/mainwindow.ui -o build/ui_mainwindow.h

build/ui_qsqlconnectiondialog.h: ui/qsqlconnectiondialog.ui
	/usr/bin/uic-qt4 ui/qsqlconnectiondialog.ui -o build/ui_qsqlconnectiondialog.h

build/ui_record.h: ui/record.ui
	/usr/bin/uic-qt4 ui/record.ui -o build/ui_record.h

build/ui_addroom.h: ui/addroom.ui
	/usr/bin/uic-qt4 ui/addroom.ui -o build/ui_addroom.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_rcc_clean compiler_uic_clean 

####### Compile

build/login.o: src/login.cpp build/ui_login.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/login.o src/login.cpp

build/main.o: src/main.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/main.o src/main.cpp

build/mainwindow.o: src/mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/mainwindow.o src/mainwindow.cpp

build/qsqlconnectiondialog.o: src/qsqlconnectiondialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/qsqlconnectiondialog.o src/qsqlconnectiondialog.cpp

build/AdminCheck.o: src/AdminCheck.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/AdminCheck.o src/AdminCheck.cpp

build/AddRoom.o: src/AddRoom.cpp build/ui_addroom.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/AddRoom.o src/AddRoom.cpp

build/check.o: src/check.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/check.o src/check.cpp

build/show.o: src/show.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/show.o src/show.cpp

build/liveinfo.o: src/liveinfo.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/liveinfo.o src/liveinfo.cpp

build/moc_login.o: build/moc_login.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/moc_login.o build/moc_login.cpp

build/moc_mainwindow.o: build/moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/moc_mainwindow.o build/moc_mainwindow.cpp

build/moc_qsqlconnectiondialog.o: build/moc_qsqlconnectiondialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/moc_qsqlconnectiondialog.o build/moc_qsqlconnectiondialog.cpp

build/moc_AdminCheck.o: build/moc_AdminCheck.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/moc_AdminCheck.o build/moc_AdminCheck.cpp

build/moc_AddRoom.o: build/moc_AddRoom.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/moc_AddRoom.o build/moc_AddRoom.cpp

build/moc_check.o: build/moc_check.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/moc_check.o build/moc_check.cpp

build/moc_liveinfo.o: build/moc_liveinfo.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/moc_liveinfo.o build/moc_liveinfo.cpp

build/moc_show.o: build/moc_show.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/moc_show.o build/moc_show.cpp

build/qrc_HMS.o: qrc_HMS.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/qrc_HMS.o qrc_HMS.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

